### ISSUE TITLE
TelnetDebian7 issues

### ISSUE THREAD

**Issue by alfonsocaponi** [foospidy/HoneyPy#2]
I'm using "TelnetDebian7" plugin with the last version of HoneyPy on Ubuntu 14.04.2 LTS (twistd 13.2.0). I've two issus:

1) the client need to send a "carriage return" to start the session;
2) after the "exit" command execution the prompt is printed:

admin$ exit
admin$ Connection closed by foreign host.

**Comment by foospidy** [comment]
Thank you for submitting these issues! I'll review and respond later this evening.

**Comment by foospidy** [comment]
My intention was to replace the TelnetDebian7 plugin with the TelnetUnix plugin since it uses the twisted.protocols.telnet module. So far it seems to be a better Telnet emulation and I've got better results with it. I'll look at the other issue you opened for the TelnetUnix plugin to help get that going for you.
