### ISSUE TITLE
Enhancement: Need event for "Connection Close" in Plugins

### ISSUE THREAD

**Issue by ameygat** [foospidy/HoneyPy#25]
I was editing plugin file for example:
https://github.com/foospidy/HoneyPy/blob/master/plugins/TelnetDebian7/TelnetDebian7.py

I wanted some log to be created at connection close event but didnt found any sample function which is doing this. May I know if there is a event generated for connection close event ? Or some addition can be done to get this event generated ?

**Comment by foospidy** [comment]
Since it is leveraging the twisted framework there may be a connectionLost method available, here's an example
https://github.com/foospidy/HoneyPy/blob/master/lib/honeypy_console.py#L131

Please give it a try and see if that does what you need.

Just a side note, TelnetUnix is a better telnet plugin. I recommend using that one instead.

**Comment by ameygat** [comment]
Thanks I will try that.

**Comment by ameygat** [comment]
Yup that function works on connection close. Thanks alot, also thanks for pointing to TelnetUnix plugin.

**Comment by foospidy** [comment]
Great! I'm glad you were able to resolve it!
