### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by t3chn0m4g3** [foospidy/HoneyPy#66]
On January 1st 2020 Python 2.7 will reach EOL and pip will also drop Py2.7 support. Are you planning on upgrading to Python 3.x?

**Comment by foospidy** [comment]
@t3chn0m4g3 I have no plans to upgrade HoneyPy to Python 3. I've actually focused time & effort on development of the honeydb-agent (https://honeydb-agent-docs.readthedocs.io/). I recommend using the honeydb-agent instead of HoneyPy. The honeydb-agent is a self contained binary so it will run regardless of Python being installed on the host or not. So no need to have Python 2 installed on the host.

**Comment by t3chn0m4g3** [comment]
@foospidy Thanks for the swift response and pointing out HoneyDB to me. What type of license is honeydb-agent released under (could only find the honeydb-python module on GitHub).

**Comment by foospidy** [comment]
The honeydb-agent is not open sourced. However, it is free to use. Honestly, putting together an official EULA for the honeydb-agent is still on my todo list :-) Did you have any specific concerns or questions?

The honeydb-python module is just a client CLI and library for interacting with the HoneyDB API. You can find more on that here: https://honeydb.io/threats

**Comment by t3chn0m4g3** [comment]
Thanks :bowtie: Is it legally OK to integrate honeydb-agent as a docker image in [T-Pot](https://github.com/dtag-dev-sec/tpotce) which basically will use [this config](https://github.com/dtag-dev-sec/tpotce/tree/master/docker/honeypy/dist)?

**Comment by foospidy** [comment]
Yes it is ok. I'll take a look at your config as there might be some differences in implementation.

**Comment by t3chn0m4g3** [comment]
Thank you, very much appreciated!
